### ISSUE TITLE
NULL byte?

### ISSUE THREAD

**Issue by tbuchok** [gwk/csv-to-sqlite#1]
```
Traceback (most recent call last):
  File "csv-to-sqlite.py", line 371, in <module>
    if __name__ == '__main__': main()
  File "csv-to-sqlite.py", line 77, in main
    load_table(db=db, csv_path=csv_path, table=table, dialect=dialect)
  File "csv-to-sqlite.py", line 110, in load_table
    col_names, columns = infer_columns(header, reader)
  File "csv-to-sqlite.py", line 145, in infer_columns
    for i, row in enumerate(reader, 1):
_csv.Error: line contains NULL byte
```

**Comment by tbuchok** [comment]
i can't send over the file in the issue -- it's big and has PII -- so let me know and we can debug another time.
